logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
enabled = false
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default and only applies included-patches
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
# With oled
# excluded-patches = "custom-branding-name custom-branding-icon-revancify custom-branding-icon-afn-red custom-branding-icon-afn-blue custom-branding-icon-mmt debugging"
# Without oled
# old excluded-patches = "custom-branding-name custom-branding-icon-revancify custom-branding-icon-afn-red custom-branding-icon-afn-blue custom-branding-icon-mmt theme debugging"
excluded-patches = "custom-branding-icon-afn-blue custom-branding-icon-afn-red custom-branding-icon-mmt custom-branding-icon-revancify-blue custom-branding-icon-revancify-red custom-branding-name translations debugging theme"
# Add materialyou
included-patches = "materialyou"

[Music]
enabled = false
build-mode = "both"
app-name = "Music"
excluded-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "both"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
excluded-patches = "custom-branding-music-afn-blue custom-branding-music-afn-red custom-branding-music-mmt custom-branding-music-revancify-blue custom-branding-music-revancify-red amoled custom-branding-music-name"

[Twitter]
enabled = false
build-mode = "apk"
excluded-patches = "hide-views-stats"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"

[Twitch]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[TikTok]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
dpi = "560-640dpi"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
arch = "arm64-v8a"

[Backdrops]
enabled = false
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
arch = "arm64-v8a"

[Tasker]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
