logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations
# you can use rvmm-config-gen to generate a config

# for tablet use 'Enable tablet layout' 'Tablet mini player' in included-patches

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"
included-patches = "'Enable tablet layout' 'Tablet mini player' 'Remove tracking query parameter' 'Vanced MicroG support' 'Minimized playback' 'Client spoof' 'Bypass URL redirects' 'Open links externally' 'HDR auto brightness' 'Restore old video quality menu' 'Remember video quality' 'Seekbar tapping' 'Disable precise seeking gesture' 'External downloads' 'Return YouTube Dislike' 'Disable suggested video end screen' 'Disable fullscreen ambient mode' 'Hide album cards' 'Hide filter bar' 'Hide floating microphone button' 'Hide breaking news shelf' 'Hide crowdfunding box' 'Hide endscreen cards' 'Hide layout components' 'Hide video action buttons' 'Hide cast button' 'Navigation buttons' 'Theme' 'Restore old seekbar thumbnails' 'SponsorBlock' 'Disable player popup panels' 'Video ads' 'Hide ads'"
exclusive-patches = true

[Music]
enabled = false
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-arch = "both"

[Music-Extended]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Twitter]
enabled = false
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Twitch]
enabled = false
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[TikTok]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
enabled = false
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Lightroom]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
apkmirror-arch = "arm64-v8a"

[Backdrops]
enabled = false
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
apkmirror-arch = "arm64-v8a"

[Tasker]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
