enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
app-name = "Yomaru"
rv-brand = "Revanced"
version = "auto"
arch = "arm64-v8a"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
excluded-patches = ""
included-patches = ""
patcher-args = """\
  -OAppIcon=icons \
  -OAppName=YoMaruExT \
   """


# # │ Revanced Extenends here │       RVX
# [RvX] #
# app-name = "Yomaru"
# rv-brand = "Ext-rvx"
# patches-source = "inotia00/revanced-patches"
# cli-source = "inotia00/revanced-cli"
# integrations-source = "inotia00/revanced-integrations"
# build-mode = "apk"                                                # apk = "apk" or magisk zip = "module"
# arch = "arm64-v8a"
# version = "auto"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# # included-patches = "'Custom header for YouTube' 'Hide Shorts dimming'"
# # excluded-patches = "'Custom branding icon for YouTube'"
# excluded-patches = ""
# included-patches = ""

