logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/cvnertnc/rvx-app/blob/main/CONFIG.md for more detailed explanations

[YouTube-j-hc]
app-name = "YouTube"
patches-source = "ReVanced/revanced-patches"
integrations-source = "ReVanced/revanced-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[YouTube-inotia00]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music-j-hc]
app-name = "Music"
patches-source = "ReVanced/revanced-patches"
integrations-source = "ReVanced/revanced-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"

[Music-inotia00]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"

[YouTube-cvnertnc]
patches-version = "v2.195.1"
integrations-version = "v0.120.1"
cli-version = "v4.0.2"
rv-brand = "RVX Youtube"
build-mode = "apk"
excluded-patches = "'MaterialYou' 'Append time stamps information' 'Custom branding YouTube name' 'Custom branding icon Revancify blue' 'Custom double tap length' 'Custom package name' 'Custom seekbar color' 'Disable hdr video' 'Disable pip notification' 'Enable gradient loading screen' 'Enable old quality layout' 'Enable seekbar tapping' 'Enable wide search bar' 'Header switch' 'Hide account menu' 'Hide captions button' 'Hide cast button' 'Hide collapse button' 'Hide comment component' 'Hide description components' 'Hide feed flyout panel' 'Hide filmstrip overlay' 'Hide floating microphone' 'Hide handle' 'Hide latest videos button' 'Hide load more button' 'Hide player button background' 'Hide player flyout panel' 'Hide quick actions' 'Hide snack bar' 'Hide suggested video overlay' 'Hide time stamp' 'Hide tooltip content' 'Overlay buttons' 'Swipe controls' 'Theme' 'Hide double tap overlay filter'"
included-patches = "'Add splash animation' 'Custom branding icon Revancify red' 'Force premium heading'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[YouTubeMY-cvnertnc]
patches-version = "v2.195.1"
integrations-version = "v0.120.1"
cli-version = "v4.0.2"
rv-brand = "RVX Youtube"
build-mode = "both"
excluded-patches = "'Append time stamps information' 'Custom branding YouTube name' 'Custom branding icon Revancify blue' 'Custom double tap length' 'Custom package name' 'Custom seekbar color' 'Disable hdr video' 'Disable pip notification' 'Enable gradient loading screen' 'Enable old quality layout' 'Enable seekbar tapping' 'Enable wide search bar' 'Header switch' 'Hide account menu' 'Hide captions button' 'Hide cast button' 'Hide collapse button' 'Hide comment component' 'Hide description components' 'Hide feed flyout panel' 'Hide filmstrip overlay' 'Hide floating microphone' 'Hide handle' 'Hide latest videos button' 'Hide load more button' 'Hide player button background' 'Hide player flyout panel' 'Hide quick actions' 'Hide snack bar' 'Hide suggested video overlay' 'Hide time stamp' 'Hide tooltip content' 'Overlay buttons' 'Swipe controls' 'Theme' 'Hide double tap overlay filter'"
included-patches = "'Add splash animation' 'Custom branding icon Revancify red' 'Force premium heading' 'MaterialYou'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Music-cvnertnc]
patches-version = "v2.195.1"
integrations-version = "v0.120.1"
cli-version = "v4.0.2"
rv-brand = "RVX Music"
build-mode = "both"
excluded-patches = "'Custom branding Music name' 'Custom branding icon Revancify blue' 'Custom package name' 'Enable old style library shelf' 'Enable old style miniplayer' 'Spoof app version'"
included-patches = "'Custom branding icon Revancify red'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"
