enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" 
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "both"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "both"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" 
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-anddea]
enabled = true
app-name = "Music"
version = "auto"
patches-source = "anddea/revanced-patches"
patches-version = "v2.225.0-dev.21"
integrations-source = "anddea/revanced-integrations"
integrations-version = "v0.152.0-dev.12"
rv-brand = "anddea"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "both"

[YouTube-anddea]
enabled = true
app-name = "YouTube"
version = "auto"
patches-source = "anddea/revanced-patches"
patches-version = "v2.225.0-dev.21"
integrations-source = "anddea/revanced-integrations"
integrations-version = "v0.152.0-dev.12"
rv-brand = "anddea"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" 
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Twitter]
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
arch = "all"

[Twitch]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
arch = "both"

[TikTok]
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
# arch = "armeabi-v7a, arm64-v8a"
included-patches = "'SIM spoof'"

[Reddit]
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Messenger]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
# arch = "armeabi-v7a"

[Facebook]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
# arch = "armeabi-v7a"

[Spotify]
enabled = false
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Spotify-Lite]
enabled = true
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://spotify-lite.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
arch = "arm64-v8a"

[Backdrops]
enabled = false
version = "auto"
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[MyExpenses]
enabled = true
version = "auto"
uptodown-dlurl = "https://my-expenses.en.uptodown.com/android"

[NyxMusicPlayer]
enabled = true
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://nyx-music-player.en.uptodown.com/android"
arch = "both"

[IconPackStudio]
enabled = true
version = "auto"
uptodown-dlurl = "https://icon-pack-studio.en.uptodown.com/android"

[TickTick]
enabled = true
version = "auto"
uptodown-dlurl = "https://ticktick.en.uptodown.com/android"
arch = "both"

[Tasker]
enabled = true
uptodown-dlurl = "https://tasker.en.uptodown.com/android"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"

# [Instagram]
# enabled = true
# version = "auto"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Instagram]
enabled = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.instagram.android"
arch = "arm64-v8a"

[InShorts]
enabled = true
version = "auto"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
arch = "both"

[SyncForReddit]
enabled = false
version = "auto"
uptodown-dlurl = "https://sync-for-reddit.en.uptodown.com/android"

[InfinityForReddit]
enabled = true
version = "auto"
uptodown-dlurl = "https://infinity-for-reddit.en.uptodown.com/android"

[VSCO]
enabled = true
version = "auto"
uptodown-dlurl = "https://vsco-cam.en.uptodown.com/android"
arch = "both"

[Pixiv]
enabled = true
version = "auto"
uptodown-dlurl = "https://pixiv.en.uptodown.com/android"

[Trakt]
enabled = false
version = "auto"
# uptodown-dlurl = "https://trakt.en.uptodown.com/android"

[MemeGenerator]
enabled = true
version = "auto"
uptodown-dlurl = "https://meme-generator-free.en.uptodown.com/android"

[Lightroom]
enabled = true
version = "auto"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
arch = "both"

[Tumblr]
enabled = true
version = "auto"
uptodown-dlurl = "https://tumblr.en.uptodown.com/android"
