logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "both"
excluded-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"                                                     # both arm64-v8a and arm-v7a

[Twitter]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"

[Twitch]
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Lightroom]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "both"

[Spotify]
enabled = true
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Spotify-Lite]
enabled = true
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://spotify-lite.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
apkmirror-arch = "arm64-v8a"

[Backdrops]
enabled = true
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[MyExpenses]
enabled = true
uptodown-dlurl = "https://my-expenses.en.uptodown.com/android"

[NyxMusicPlayer]
enabled = true
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://nyx-music-player.en.uptodown.com/android"

[IconPackStudio]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
apkmirror-arch = "both"

[Tasker]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"

[Instagram]
enabled = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "both"

[InShorts]
enabled = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshorts-formerly-news-in-shorts/inshorts-news-in-60-words-2/"
apkmirror-arch = "both"

[Music-Extended]
enabled = true
app-name = "Music"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "ReVanced Extended Fork ReX"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"

[YouTube-Extended] 
enabled = true
app-name = "YouTube"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "revanced/revanced-cli"
rv-brand = "ReVanced Extended Fork ReX"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

