logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-arch = "both"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-arch = "both"

[Twitter]
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Twitch]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Lightroom]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "both"

[Spotify]
enabled = false
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Spotify-Lite]
enabled = false
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://spotify-lite.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
apkmirror-arch = "arm64-v8a"

[Backdrops]
enabled = true
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[MyExpenses]
enabled = false
uptodown-dlurl = "https://my-expenses.en.uptodown.com/android"

[NyxMusicPlayer]
enabled = false
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://nyx-music-player.en.uptodown.com/android"

[IconPackStudio]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
apkmirror-arch = "both"

[Tasker]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"

[Instagram]
enabled = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "both"

[InShorts]
enabled = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshorts-formerly-news-in-shorts/inshorts-news-in-60-words-2/"
apkmirror-arch = "both"

[SyncForReddit]
enabled = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/red-apps-ltd/sync-for-reddit/"

[InfinityForReddit]
enabled = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit/"

