enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Extended-anddea]
enabled = true
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced Extended anddea"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "yt-rvx-anddea"
arch = "all"


[YouTube-Music-Extended-anddea]
enabled = true
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
rv-brand = "ReVanced Extended anddea"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "ytm-rvx-anddea"
arch = "all"


[YouTube-Morephe]
enabled = false
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "yt-morphe"
arch = "all"


[YouTube-Music-Morphe]
enabled = false
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "ytm-morphe"
arch = "all"

[YouTube-Morphe]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "both"
rv-brand = "Morphe"
