
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube-RV]
enabled = true
app-name = "YouTube"
build-mode = "apk"
excluded-patches = "'Return YouTube Dislike' 'Premium heading' 'Alternative thumbnails'"
included-patches = "'Enable slide to seek'"
version = "auto"
rv-brand = "RV"
#cli-version = "v4.4.1"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
#cli-source = "Revanced/revanced-cli"


[Music-RV]
enabled = true
app-name = "Music"
rv-brand = "RV"
build-mode = "apk"
#cli-version = "v4.4.1"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
#uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"
version="6.51.53"
excluded-patches = "'Amoled' 'Change start page' 'Custom branding icon YouTube Music' 'Custom package name' 'Return YouTube Dislike'"
#cli-source = "Revanced/revanced-cli"

[YouTube-RX]
enabled = true
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RX"
build-mode = "apk"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
excluded-patches = "'Custom package name' 'Return YouTube Dislike' 'Custom branding heading' 'Custom branding icon YouTube' 'Alternative thumbnails'"
included-patches = "'Enable song search' 'MaterialYou' 'Theme'"
#version="19.05.36"
#cli-version = "v4.1.1"


[Music-RX]
enabled = true
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RX"
build-mode = "apk"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
#uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
version="6.51.53"
excluded-patches = "'Amoled' 'Change start page' 'Custom branding icon YouTube Music' 'Custom package name' 'Return YouTube Dislike'"

[YouTube-RVX]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RvX"
build-mode = "apk"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
excluded-patches = "'Custom package name' 'Return YouTube Dislike' 'Premium heading' 'Custom branding icon YouTube'"
included-patches = "'Enable song search' 'MaterialYou' 'Theme'"
#version="18.45.43"
#cli-version = "v4.1.1"


[Music-RVX]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
build-mode = "apk"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"
#version="6.33.52"
excluded-patches = "'Amoled' 'Change start page' 'Custom branding icon YouTube Music' 'Custom package name' 'Return YouTube Dislike'"

[YouTube-Android7]
enabled = false
app-name = "YouTube"
patches-source = "kitadai31/revanced-patches-android6-7"
integrations-source = "kitadai31/revanced-integrations"
cli-source = "revanced/rvcli"
rv-brand = "RevancedOld"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "custom-branding-name theme custom-package-name custom-branding-icon-revancify-blue debugging materialyou premium-heading custom-branding-icon-afn-blue custom-branding-icon-revancify custom-branding-icon-afn-red return-youtube-dislike"                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""
