[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced"
build-mode = "module"

