logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Spoof device dimensions' 'Minimized playback' 'Remember video quality' 'HDR auto brightness' 'Playback speed' 'Video ads' 'Hide ads' 'Copy video url' 'Swipe controls' 'Disable fine scrubbing gesture' 'External downloads' 'Hide Shorts components' 'Hide filter bar' 'Hide email address' 'Tablet mini player' 'Disable Shorts on startup' 'SponsorBlock' 'Theme' 'Disable player popup panels'"
exclusive-patches = true

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Permanent repeat' 'Permanent shuffle'"
excluded-patches = "'Vanced MicroG support' 'Bypass certificate checks'"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Twitter]
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Twitch]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Lightroom]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
apkmirror-arch = "arm64-v8a"

[Backdrops]
enabled = false
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
apkmirror-arch = "arm64-v8a"

[Tasker]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
