name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/6 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Should build?
        id: should_build
        shell: bash
        run: |
          source utils.sh
          toml_prep "$(cat config.toml)"

          is_youtube_latest() {
            v=$(toml_get "YouTube" "version") || version=""
            if [ "$v" = latest ]; then
              declare -r cur_yt=$(sed -n 's/.*YouTube: \(.*\)/\1/p' build.md | xargs)
              [ -z "$cur_yt" ] && return 1 # empty, fail=>dont build
              declare -r last_ver=$(get_apk_vers "https://www.apkmirror.com/uploads/?appcategory=youtube" | get_largest_ver)

              echo "current yt version: $cur_yt"
              echo "latest yt version: $last_ver"
              [ "$cur_yt" != "$last_ver" ] # test success=>build, fail=>dont build
            else
              return 1 # not experimental, dont build
            fi
          }

          is_cli_latest() {
            declare -r last_cli_url=$(req https://api.github.com/repos/revanced/revanced-cli/releases/latest - | json_get 'browser_download_url')
            declare -r last_cli=${last_cli_url##*/}
            cur_cli=$(sed -n 's/.*CLI: \(.*\)/\1/p' build.md | xargs)

            echo "current integrations version: $cur_cli"
            echo "latest integrations version: $last_cli"
            [ "$cur_cli" != "$last_cli" ] # test success=>build, fail=>dont build
          }

          is_integrations_latest() {
            mkdir -p temp
            last_integrations_url=$(req https://api.github.com/repos/revanced/revanced-integrations/releases/latest - | json_get 'browser_download_url')
            last_integrations_apk=${last_integrations_url##*/}
            last_integrations="${last_integrations_apk%.apk}-$(cut -d/ -f8 <<<"$last_integrations_url").apk"
            cur_integrations=$(sed -n 's/.*Integrations: \(.*\)/\1/p' build.md | xargs)

            echo "current integrations version: $cur_integrations"
            echo "latest integrations version: $last_integrations"
            [ "$cur_integrations" != "$last_integrations" ] # test success=>build, fail=>dont build
          }

          is_patches_latest() {
            declare -r last_patches_url=$(wget -nv -O- https://api.github.com/repos/revanced/revanced-patches/releases/latest | json_get 'browser_download_url' | grep 'jar')
            declare -r last_patches=${last_patches_url##*/}
            cur_patches=$(sed -n 's/.*Patches: \(.*\)/\1/p' build.md | xargs)

            echo "current patches version: $cur_patches"
            echo "latest patches version: $last_patches"
            [ "$cur_patches" != "$last_patches" ] # test success=>build, fail=>dont build
          }

          if ! git checkout update; then
            echo "first time building!"
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          elif is_youtube_latest || is_cli_latest || is_integrations_latest || is_patches_latest; then
            echo "build!"
            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
          else
            echo "dont build!"
            echo "SHOULD_BUILD=0" >> $GITHUB_OUTPUT
          fi

    outputs:
      SHOULD_BUILD: ${{ steps.should_build.outputs.SHOULD_BUILD }}

  build:
    needs: check
    uses: ./.github/workflows/build.yml
    if: ${{ needs.check.outputs.SHOULD_BUILD == 1 }}
    secrets:
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
