name: Act on release

on: 
  workflow_call:
    secrets:
      TELEGRAM_TO:
        required: true
      TELEGRAM_TOKEN:
        required: true
    inputs:
      release_tag:
        type: string
        description: 'The tag of the release'
        required: true
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: 'The tag of the release'
        required: true
      

jobs:
  Notify_Release:
    name: Notify Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # The python version to use.
          cache: 'pip'
          cache-dependency-path: 'telegram-script/requirements.txt'
        
      - name: Install dependencies
        run: pip install -r telegram-script/requirements.txt
     
      - name: Run telegram notification script
        run: python3 telegram-script
          
      - name: Telegram Channel Update
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message_file: release_notification.md
  
  push_notification:
    name: Push Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # The python version to use.
          cache: 'pip'
          cache-dependency-path: 'push-notify/requirements.txt'

      - name: Install dependencies
        run: pip install -r push-notify/requirements.txt

      - name: Create google-auth json
        run: echo "${{ secrets.GOOGLE_AUTH_JSON }}" | base64 -d > google-services.json

      - name: Run push notification script
        run: |
          release_tag=${{ github.event.inputs.release_tag }}
          release_body=$(gh release view $release_tag --json body -q .body)
          python3 push-notify --title "New Release $release_tag" --body "$release_body" --api_url ${{ secrets.NOTIF_API_URL }} --bearer ${{ secrets.NOTIF_API_BEARER }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
