name: Act on release

on: [workflow_call, workflow_dispatch]

jobs:
  Notify_Release:
    name: Notify Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          
      - name: Switch to release branch
        run: git checkout -f release || git switch --discard-changes --orphan update
        
      - name: Update release JSON
        run: |
          curl https://api.github.com/repos/${{ github.repository }}/releases/latest > release.json
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
          
      - name: Push release.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: release
          skip_checkout: true
          file_pattern: release.json
          commit_message: Update release.json on ${{ steps.date.outputs.date }}
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: jannekem/run-python-script-action@v1
        id: pyscript
        with:
          script: |
            import json

            # Read release.json file
            with open('release.json', 'r') as f:
                release = json.load(f)

            print("Date: "+release['body'], end="\n\n")

            print("*__Downloads__*")

            # Collect browser_download_url from assets in release
            for asset in release['assets'][::-1]:
                print(f"[{asset['name'].replace("-","\-")}]({asset['browser_download_url']})")
          
      - name: Telegram Channel Update
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdownV2
          message: |
            *__RELEASE__*
            
            ${{ steps.pyscript.outputs.stdout }}
            
            Visit [ReVanced APKs](https://revanced-apks.pages.dev/)
            
            Follow @revanced_apks_web
