name: Sync Upstream

env:
  UPSTREAM_URL: "https://github.com/j-hc/revanced-magisk-module.git"
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  UPSTREAM_BRANCH: "main"
  DOWNSTREAM_BRANCH: "main"

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Upstream
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
