name: Update release metadata

on:
    workflow_dispatch:

jobs:
  release-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Prepare build.md
        run: |
            if git checkout origin/update build.md; then
            filename="build.md"
            ./extras.sh "revanced/revanced-integrations" "revanced/revanced-patches" "revanced/revanced-cli" > $filename
            echo -e "\n\n" >> $filename
            ./extras.sh "YT-Advanced/ReX-integrations" "YT-Advanced/ReX-patches" "revanced/revanced-cli" >> $filename
            fi

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            branch: update
            skip_checkout: true
            file_pattern: build.md
            commit_message: Bump version